name: vuetemplate

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm update
          npm run build
          npm install sortablejs@^1.14.0 --save
            npm install vue-draggable-next@latest --save

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

              nvm install 14
              rm -rf node_modules
              npm install -g pm2
              npm install webpack@^5.0.0 --save-dev
              npm install file-loader@latest --save-dev
              npm install sortablejs@^1.14.0 --save
              npm install vue-draggable-next@latest --save
              cd ~/vue-template
              git fetch origin
              git remote -v
              git pull origin main
              npm install
              npm update
              npm run build
              pm2 restart api       
    
